param(
    [Parameter(Mandatory = $true)][string]$Source,
    [Parameter(Mandatory = $true)][string]$OutCs
)

# Reads the Battle.net Password.dll .auth cache on the BUILD machine and
# emits a generated C# file so the distributed launcher exe is self-contained.
# The .auth blob is never committed to source.

if (-not (Test-Path -LiteralPath $Source)) {
    throw "AuthModule source missing: $Source"
}

$bytes = [IO.File]::ReadAllBytes($Source)
if ($bytes.Length -lt 64 -or $bytes[0] -ne 0x4D -or $bytes[1] -ne 0x5A) {
    throw "AuthModule source is not a PE .auth file: $Source"
}

$b64 = [Convert]::ToBase64String($bytes)
$outDir = Split-Path -Parent $OutCs
if ($outDir) {
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}

$nl = [Environment]::NewLine
$body = "// <auto-generated />$nl" +
    "namespace SkyFireLauncher.Realm;$nl$nl" +
    "internal static class AuthModuleBlob$nl{$nl" +
    "    internal static byte[] Load() => System.Convert.FromBase64String($nl" +
    "        `"$b64`");$nl}$nl"
[IO.File]::WriteAllText($OutCs, $body)
