<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SkyFireLauncher</AssemblyName>
    <RootNamespace>SkyFireLauncher</RootNamespace>
    <ApplicationTitle>SkyFire Launcher</ApplicationTitle>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>

    <BaseOutputPath>..\..\Build\</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="AppIcon.ico" />
    <Resource Include="Assets\skyfire-launcher-logo.png" />
    <Resource Include="Fonts\*.ttf" />
    <Resource Include="Fonts\*.otf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkyFireLauncher.Core\SkyFireLauncher.Core.csproj" />
  </ItemGroup>

</Project>
