<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SkyFireLauncher</AssemblyName>
    <RootNamespace>SkyFireLauncher</RootNamespace>
    <ApplicationTitle>SkyFire Launcher</ApplicationTitle>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <Version>1.4.0</Version>
    <InformationalVersion>1.4 Authnet</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Copyright>Copyright © 2026 Project SkyFire</Copyright>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/ProjectSkyfire/launcher</RepositoryUrl>

    <BaseOutputPath>..\..\Build\</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="AppIcon.ico" />
    <Resource Include="Assets\skyfire-launcher-logo.png" />
    <Resource Include="Fonts\*.ttf" />
    <Resource Include="Fonts\*.otf" />
    <EmbeddedResource Include="AuthModules\*.auth" />
  </ItemGroup>

</Project>
